import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { basename } from 'path';
import { RepoDigestResult } from './types.js';
import { walkRepoFiles, looksBinary } from './fsUtils.js';
import { getRepoDigestsRoot, getDigestPath, getDigestSkippedPath } from './paths.js';

interface SkippedFile {
  path: string;
  reason: string;
}

const SKIP_DIRS = [
  '.git/', 'node_modules/', 'dist/', 'build/', '.next/', '.venv/', 'venv/',
];

const SKIP_EXT = [
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.mp4', '.mov', '.avi', '.zip', '.tar',
  '.gz', '.7z', '.pdf', '.woff', '.woff2', '.ttf', '.ico', '.exe', '.dll', '.so', '.dylib',
];

const INCLUDE_NAMES = new Set(['README.md', 'README', 'package.json', 'pyproject.toml', 'go.mod', 'Cargo.toml']);

function shouldSkip(rel: string): string | null {
  const lower = rel.toLowerCase();
  if (SKIP_DIRS.some((d) => lower.includes(d))) return 'ignored-directory';
  if (lower.endsWith('.env') || lower.includes('.env.')) return 'secret-env-file';
  if (lower.includes('id_rsa') || lower.endsWith('.pem') || lower.endsWith('.key')) return 'secret-key-file';
  if (lower.includes('package-lock.json') || lower.includes('pnpm-lock.yaml') || lower.includes('yarn.lock')) return 'lockfile-skipped';
  if (SKIP_EXT.some((ext) => lower.endsWith(ext))) return 'binary-or-media';
  return null;
}

export function generateSafeDigest(repoId: string, repoPath: string): RepoDigestResult {
  mkdirSync(getRepoDigestsRoot(), { recursive: true });
  const files = walkRepoFiles(repoPath, 15_000);

  const skipped: SkippedFile[] = [];
  const chunks: string[] = [];
  let included = 0;

  for (const file of files) {
    const rel = file.relativePath;
    const skipReason = shouldSkip(rel);
    if (skipReason) {
      skipped.push({ path: rel, reason: skipReason });
      continue;
    }
    if (file.size > 200_000) {
      skipped.push({ path: rel, reason: 'file-too-large' });
      continue;
    }

    const raw = readFileSync(file.absolutePath);
    if (looksBinary(raw)) {
      skipped.push({ path: rel, reason: 'binary-content' });
      continue;
    }

    const isPriority = INCLUDE_NAMES.has(basename(rel));
    const text = raw.toString('utf-8');
    if (!isPriority && text.trim().length === 0) {
      continue;
    }
    const body = text.slice(0, 12_000);
    chunks.push(`## ${rel}\n\n\`\`\`\n${body}\n\`\`\``);
    included += 1;
    if (included >= 220) break;
  }

  const digestPath = getDigestPath(repoId);
  const skippedPath = getDigestSkippedPath(repoId);
  const digest = `# Safe Digest: ${repoId}

Generated by BuilderBrain (read-only analysis). This digest never executes repo code.

${chunks.join('\n\n')}
`;

  writeFileSync(digestPath, digest, 'utf-8');
  writeFileSync(skippedPath, JSON.stringify(skipped, null, 2), 'utf-8');

  return {
    repoId,
    digestPath,
    skippedPath,
    includedFiles: included,
    skippedFiles: skipped.length,
  };
}
