/**
 * Self-Healing Background Worker
 * 
 * Runs silently when the machine is idle. Reads runs logs,
 * identifies errors, and drafts bug fix proposals for review.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { routeChat } from './aiRouter.js';

export async function runSelfHealer(): Promise<number> {
  const runsDir = join(process.cwd(), 'brain-data', 'runs');
  const proposalsDir = join(process.cwd(), 'brain-data', 'proposals');
  
  mkdirSync(proposalsDir, { recursive: true });

  let healedCount = 0;

  try {
    const files = readdirSync(runsDir).filter(f => f.endsWith('.json'));
    
    for (const file of files) {
      const runLog = JSON.parse(readFileSync(join(runsDir, file), 'utf-8'));
      
      // If there's an error logged in the run
      if (runLog.summary?.toLowerCase().includes('error') || runLog.risk === 'Critical') {
        const patchName = `patch-${file.replace('.json', '.md')}`;
        
        // Skip if we already proposed a patch
        if (readdirSync(proposalsDir).includes(patchName)) continue;

        console.log(`[SelfHealer] Analyzing failing run: ${file}`);
        
        const messages = [
          {
            role: 'system',
            content: 'You are the BuilderBrain Self-Healer. Analyze the failed execution log and propose a code fix. Output the patch as a markdown file.'
          },
          {
            role: 'user',
            content: `Failed Run Data:\n\n${JSON.stringify(runLog, null, 2)}`
          }
        ];

        // Ensure we handle chat format correctly for our aiRouter interface
        const result = await routeChat(messages as any);
        
        const proposalContent = `# Proposed Fix for ${file}\n\nGenerated by Self-Healer overnight.\n\n${result.text}`;
        writeFileSync(join(proposalsDir, patchName), proposalContent, 'utf-8');
        
        healedCount++;
      }
    }
    
    return healedCount;
  } catch (err) {
    console.error(`[SelfHealer] Engine failed: ${err}`);
    return 0;
  }
}
